apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elt-platform.fullname" . }}-worker
  labels:
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elt-platform.fullname" . }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elt-platform.fullname" . }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ include "elt-platform.apiImage" . }}
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - core.celery_app.celery_app
            - worker
            - --loglevel=info
            - -Q
            - celery,notifications
          envFrom:
            - secretRef:
                name: {{ include "elt-platform.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "elt-platform.fullname" . }}-api-config
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
