#!/usr/bin/env python3
"""Render .env and deployment metadata from a deployment config JSON file."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any
from urllib.parse import quote_plus


def _public_base_url(host: str, port: int, use_proxy: bool) -> str:
    if use_proxy and port == 80:
        return f"http://{host}"
    if use_proxy and port == 443:
        return f"https://{host}"
    return f"http://{host}:{port}"


def _database_url(config: dict[str, Any]) -> tuple[str, str, str]:
    db = config["database"]
    user = db["user"]
    password = quote_plus(db["password"])
    elt_db = db.get("elt_db_name", "elt_metadata")

    if db["source"] == "bundled":
        host = "postgres"
        port = 5432
    else:
        host = db["host"]
        port = db.get("port", 5432)

    return (
        f"postgresql://{user}:{password}@{host}:{port}/{elt_db}",
        user,
        db["password"],
    )


def render_env(config: dict[str, Any]) -> str:
    mode = config["mode"]
    db = config["database"]
    kc = config["keycloak"]
    app = config.get("app", {})
    database_url, pg_user, pg_password = _database_url(config)

    lines: list[str] = [
        "# Generated by etl-deployment/renderer/render.py",
        f"# mode={mode}",
        "",
    ]

    if mode == "monolith":
        mono = config["monolith"]
        host = mono.get("public_host", "localhost")
        use_proxy = mono.get("use_proxy", True)
        ports = mono.get("ports", {})
        http_port = ports.get("http", 80)
        api_port = ports.get("api", 8000)
        frontend_port = ports.get("frontend", 3000)
        keycloak_port = ports.get("keycloak", 8081)

        app_url = _public_base_url(host, http_port, use_proxy)
        if use_proxy:
            next_public_api = f"{app_url}/api/v1"
            kc_public = f"http://{host}:{keycloak_port}"
        else:
            next_public_api = f"http://{host}:{api_port}/api/v1"
            kc_public = f"http://{host}:{keycloak_port}"

        lines.extend([
            f"APP_URL={app_url}",
            f"HTTP_PORT={http_port}",
            f"API_PORT={api_port}",
            f"FRONTEND_PORT={frontend_port}",
            f"NEXT_PUBLIC_API_URL={next_public_api}",
            "",
        ])
    else:
        dist = config["distributed"]
        services = dist.get("services", {})
        frontend = services.get("frontend", {})
        backend = services.get("backend", {})
        auth = services.get("auth", {})
        fe_host = frontend.get("host", "localhost")
        be_host = backend.get("host", "localhost")
        auth_host = auth.get("host", "localhost")
        auth_port = auth.get("port", 8081)
        be_port = backend.get("port", 8000)
        lines.extend([
            f"APP_URL=http://{fe_host}",
            f"NEXT_PUBLIC_API_URL=http://{be_host}:{be_port}/api/v1",
            f"KC_SERVER_URL=http://{auth_host}:{auth_port}",
            f"KEYCLOAK_TOKEN_URL=http://{auth_host}:{auth_port}/realms/{kc['realm']}/protocol/openid-connect/token",
            "",
        ])

    lines.extend([
        f"IMAGE_TAG={app.get('image_tag', 'v1.0.0')}",
        "NEXT_PUBLIC_BUILD_ID=production",
        "",
        f"POSTGRES_USER={pg_user}",
        f"POSTGRES_PASSWORD={pg_password}",
        "POSTGRES_DB=postgres",
        f"ELT_DB_NAME={db.get('elt_db_name', 'elt_metadata')}",
        f"KEYCLOAK_DB_NAME={db.get('keycloak_db_name', 'keycloak')}",
        "",
        f"DATABASE_URL={database_url}",
        "REDIS_URL=redis://redis:6379/0",
        f"SANDBOX_ENABLED={'true' if app.get('sandbox_enabled', True) else 'false'}",
        "",
        f"APP_NAME={app.get('name', 'ELT Engine')}",
        "DEBUG=false",
        "",
    ])

    if mode == "monolith":
        keycloak_port = config["monolith"].get("ports", {}).get("keycloak", 8081)
        host = config["monolith"].get("public_host", "localhost")
        kc_public = f"http://{host}:{keycloak_port}"
        lines.extend([
            f"KEYCLOAK_PORT={keycloak_port}",
            f"KC_ADMIN_USER={kc['admin_user']}",
            f"KC_ADMIN_PASSWORD={kc['admin_password']}",
            "KC_SERVER_URL=http://keycloak:8080",
            f"KC_DEV_REALM={kc['realm']}",
            f"KEYCLOAK_TOKEN_URL=http://keycloak:8080/realms/{kc['realm']}/protocol/openid-connect/token",
            f"KC_ADMIN_CLIENT_ID={kc.get('admin_client_id', 'admin-cli')}",
            f"KC_ADMIN_CLIENT_SECRET={kc.get('admin_client_secret', '')}",
            "",
            f"# Public Keycloak URL (browser): {kc_public}",
        ])
    else:
        lines.extend([
            f"KC_ADMIN_USER={kc['admin_user']}",
            f"KC_ADMIN_PASSWORD={kc['admin_password']}",
            f"KC_DEV_REALM={kc['realm']}",
            f"KC_ADMIN_CLIENT_ID={kc.get('admin_client_id', 'admin-cli')}",
            f"KC_ADMIN_CLIENT_SECRET={kc.get('admin_client_secret', '')}",
        ])

    return "\n".join(lines) + "\n"


def render_manifest(config: dict[str, Any]) -> dict[str, Any]:
    """Deployment manifest consumed by control plane / bootstrap agent."""
    profile = "full" if config["mode"] == "monolith" else "distributed"
    return {
        "version": config["version"],
        "mode": config["mode"],
        "compose_profile": profile if profile == "full" else "backend",
        "database_source": config["database"]["source"],
        "generated_at": None,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Render ELT deployment artifacts")
    parser.add_argument("--config", required=True, help="Path to deployment JSON")
    parser.add_argument("--out", required=True, help="Output directory")
    args = parser.parse_args()

    config_path = Path(args.config)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    config = json.loads(config_path.read_text(encoding="utf-8"))
    env_content = render_env(config)
    manifest = render_manifest(config)

    (out_dir / ".env").write_text(env_content, encoding="utf-8")
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2),
        encoding="utf-8",
    )
    (out_dir / "deployment.json").write_text(
        json.dumps(config, indent=2),
        encoding="utf-8",
    )

    print(f"Rendered {out_dir / '.env'}")
    print(f"Rendered {out_dir / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
