# shellcheck shell=bash
# Build dt-orch-frontend for install using NEXT_PUBLIC_* from the wizard .env.
# Sourced by install.sh and rebuild-frontend-from-source.sh — do not execute directly.

frontend_install_in_installer() {
  [[ -f /.dockerenv ]] && [[ -S /var/run/docker.sock ]]
}

frontend_install_resolve_env_file() {
  local root_dir="$1"
  local state_dir="${2:-}"

  if [[ -n "${ENV_FILE:-}" && -f "${ENV_FILE}" ]]; then
    echo "${ENV_FILE}"
    return
  fi

  if [[ -n "$state_dir" && -f "${state_dir}/.env" ]]; then
    echo "${state_dir}/.env"
    return
  fi

  for vol in etl-deployment_installer_state compose_installer_state installer_state dt-orch_installer_state; do
    local mount
    mount=$(docker volume inspect "$vol" --format '{{ .Mountpoint }}' 2>/dev/null || true)
    if [[ -n "$mount" && -f "$mount/.env" ]]; then
      echo "$mount/.env"
      return
    fi
  done

  # Any docker volume ending in installer_state (compose project name varies).
  local vol_name mount
  while read -r vol_name; do
    [[ -n "$vol_name" ]] || continue
    mount=$(docker volume inspect "$vol_name" --format '{{ .Mountpoint }}' 2>/dev/null || true)
    if [[ -n "$mount" && -f "$mount/.env" ]]; then
      echo "$mount/.env"
      return
    fi
  done < <(docker volume ls -q | grep -E 'installer_state$' || true)

  if [[ -f "${root_dir}/.env" ]]; then
    echo "${root_dir}/.env"
    return
  fi

  if [[ -f "/opt/etl-deployment-state/.env" ]]; then
    echo "/opt/etl-deployment-state/.env"
    return
  fi

  echo ""
}

# Build a temporary .env from a running stack or explicit public host (when wizard volume is missing).
frontend_install_materialize_env_file() {
  local root_dir="$1"
  local public_host="${2:-}"
  local tmp="${root_dir}/.frontend-rebuild.env"
  local app_url="" kc_port="8081" api_url="" kc_url=""

  if [[ -z "$public_host" ]] && docker ps --format '{{.Names}}' | grep -qx 'dt-orch-api'; then
    app_url="$(docker inspect dt-orch-api --format '{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null \
      | grep -E '^APP_URL=' | head -1 | cut -d= -f2- || true)"
    kc_port="$(docker inspect dt-orch-api --format '{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null \
      | grep -E '^KEYCLOAK_PORT=' | head -1 | cut -d= -f2- || true)"
  fi

  if [[ -z "$public_host" && -n "$app_url" ]]; then
    public_host="$(python3 - "$app_url" <<'PY'
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or "")
PY
)"
  fi

  if [[ -z "$public_host" ]]; then
    public_host="$(curl -fsS --max-time 2 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)"
  fi

  if [[ -z "$public_host" ]]; then
    echo ""
    return 1
  fi

  kc_port="${kc_port:-8081}"
  app_url="${app_url:-http://${public_host}}"
  api_url="http://${public_host}/api/v1"
  # Keycloak is proxied on APP_URL (/realms/), not :8081 in the browser.
  kc_url="${app_url}"

  cat >"$tmp" <<EOF
# Generated by frontend-install-build.sh for rebuild-frontend-from-source.sh
APP_URL=${app_url}
NEXT_PUBLIC_API_URL=${api_url}
NEXT_PUBLIC_KC_URL=${kc_url}
KEYCLOAK_PORT=${kc_port}
NEXT_PUBLIC_KC_REALM=workspace-realm
NEXT_PUBLIC_KC_CLIENT_ID=workspace-web
IMAGE_TAG=install
FRONTEND_IMAGE=dt-orch-frontend:install
EOF
  echo "$tmp"
}

frontend_install_read_env() {
  local key="$1" file="$2"
  local line
  line=$(grep -E "^${key}=" "$file" 2>/dev/null | head -1 || true)
  [[ -n "$line" ]] || return 0
  local val="${line#*=}"
  val="${val%$'\r'}"
  val="${val#\"}"
  val="${val%\"}"
  val="${val#\'}"
  val="${val%\'}"
  printf '%s' "$val"
}

# Host path for elt-frontend checkout (Docker build context on the host daemon).
frontend_install_resolve_frontend_dir() {
  local root_dir="$1"

  if [[ -n "${ELT_FRONTEND:-}" ]]; then
    echo "${ELT_FRONTEND}"
    return 0
  fi

  local host_root="${ETL_DEPLOYMENT_HOST_ROOT:-}"
  if frontend_install_in_installer; then
    if [[ -z "$host_root" ]]; then
      echo "ERROR: ETL_DEPLOYMENT_HOST_ROOT is required to build the frontend inside the setup wizard." >&2
      return 1
    fi
    echo "$(dirname "$host_root")/elt-frontend"
    return 0
  fi

  host_root="$(cd "$root_dir" && pwd)"
  echo "$(dirname "$host_root")/elt-frontend"
}

frontend_install_host_dockerfile_exists() {
  local frontend_dir="$1"
  local name parent

  if [[ -f "${frontend_dir}/Dockerfile" ]]; then
    return 0
  fi

  if ! frontend_install_in_installer; then
    return 1
  fi

  name="$(basename "$frontend_dir")"
  parent="$(dirname "$frontend_dir")"
  docker run --rm -v "${parent}:/work:ro" alpine:3.20 test -f "/work/${name}/Dockerfile"
}

frontend_install_ensure_checkout() {
  local frontend_dir="$1"
  local repo="${ELT_FRONTEND_REPO_HTTPS:-https://github.com/chaturanga836/elt-frontend.git}"
  local ref="${ELT_FRONTEND_REF:-}"
  local name parent

  if frontend_install_host_dockerfile_exists "$frontend_dir"; then
    return 0
  fi

  name="$(basename "$frontend_dir")"
  parent="$(dirname "$frontend_dir")"

  echo "Cloning elt-frontend into ${frontend_dir} ..."
  if frontend_install_in_installer; then
    if [[ -n "$ref" ]]; then
      docker run --rm \
        -v "${parent}:/work" \
        alpine:3.20 sh -ec "
          apk add --no-cache git >/dev/null
          rm -rf /work/${name}
          git clone --depth 1 -b '${ref}' '${repo}' /work/${name}
          test -f /work/${name}/Dockerfile
        "
    else
      docker run --rm \
        -v "${parent}:/work" \
        alpine:3.20 sh -ec "
          apk add --no-cache git >/dev/null
          rm -rf /work/${name}
          git clone --depth 1 '${repo}' /work/${name}
          test -f /work/${name}/Dockerfile
        "
    fi
    return
  fi

  if command -v git >/dev/null 2>&1; then
    mkdir -p "$parent"
    if [[ -n "$ref" ]]; then
      git clone --depth 1 -b "$ref" "$repo" "$frontend_dir"
    else
      git clone --depth 1 "$repo" "$frontend_dir"
    fi
    [[ -f "${frontend_dir}/Dockerfile" ]]
    return
  fi

  if [[ -n "$ref" ]]; then
    docker run --rm \
      -v "${parent}:/work" \
      alpine:3.20 sh -ec "
        apk add --no-cache git >/dev/null
        rm -rf /work/${name}
        git clone --depth 1 -b '${ref}' '${repo}' /work/${name}
        test -f /work/${name}/Dockerfile
      "
  else
    docker run --rm \
      -v "${parent}:/work" \
      alpine:3.20 sh -ec "
        apk add --no-cache git >/dev/null
        rm -rf /work/${name}
        git clone --depth 1 '${repo}' /work/${name}
        test -f /work/${name}/Dockerfile
      "
  fi
}

# Resolve public Keycloak URL for the browser bundle (never leave localhost on customer hosts).
frontend_install_resolve_kc_url() {
  local env_file="$1"
  local kc_url api_url host port
  kc_url="$(frontend_install_read_env NEXT_PUBLIC_KC_URL "$env_file")"
  api_url="$(frontend_install_read_env APP_URL "$env_file")"
  port="$(frontend_install_read_env KEYCLOAK_PORT "$env_file")"
  port="${port:-8081}"

  if [[ -z "$kc_url" ]]; then
    kc_url="http://localhost:${port}"
  fi

  # Prefer APP_URL when wizard .env still has localhost or direct :8081 (nginx proxies /realms/).
  local app_url
  app_url="$(frontend_install_read_env APP_URL "$env_file")"
  if [[ -n "$app_url" ]]; then
    if [[ "$kc_url" == *localhost* || "$kc_url" == *127.0.0.1* || "$kc_url" == *:8081* ]]; then
      printf '%s' "$app_url"
      return
    fi
  fi

  if [[ "$kc_url" == *localhost* || "$kc_url" == *127.0.0.1* ]] && [[ -n "$api_url" ]]; then
    host="$(python3 - "$api_url" <<'PY'
import sys
from urllib.parse import urlparse
print(urlparse(sys.argv[1]).hostname or "")
PY
)"
    if [[ -n "$host" && "$host" != "localhost" && "$host" != "127.0.0.1" ]]; then
      kc_url="http://${host}"
    fi
  fi
  printf '%s' "$kc_url"
}

frontend_install_pin_frontend_image() {
  local env_file="$1"
  local tag="$2"

  if grep -q '^FRONTEND_IMAGE=' "$env_file"; then
    sed -i.bak "s|^FRONTEND_IMAGE=.*|FRONTEND_IMAGE=${tag}|" "$env_file"
  else
    echo "FRONTEND_IMAGE=${tag}" >>"$env_file"
  fi
  rm -f "${env_file}.bak"
  export FRONTEND_IMAGE="$tag"
  echo "Pinned FRONTEND_IMAGE=${tag} in ${env_file}"
}

frontend_install_restore_registry_frontend_image() {
  local env_file="$1"
  local url tag image
  url="$(frontend_install_read_env REGISTRY_URL "$env_file")"
  tag="$(frontend_install_read_env IMAGE_TAG "$env_file")"
  [[ -n "$url" && -n "$tag" ]] || return 0
  image="${url}/dt-orch-frontend:${tag}"
  frontend_install_pin_frontend_image "$env_file" "$image"
  echo "Using registry frontend image: ${image}"
}

# Build image and pin FRONTEND_IMAGE in env on success only.
frontend_install_build() {
  local root_dir="$1"
  local env_file="$2"
  local tag="${3:-dt-orch-frontend:install}"
  local frontend_dir=""

  [[ -f "$env_file" ]] || {
    echo "WARN: No .env for frontend build — using registry FRONTEND_IMAGE." >&2
    return 1
  }

  local api_url kc_url kc_realm kc_client build_id
  api_url="$(frontend_install_read_env NEXT_PUBLIC_API_URL "$env_file")"
  kc_url="$(frontend_install_resolve_kc_url "$env_file")"
  kc_realm="$(frontend_install_read_env NEXT_PUBLIC_KC_REALM "$env_file")"
  kc_client="$(frontend_install_read_env NEXT_PUBLIC_KC_CLIENT_ID "$env_file")"
  build_id="$(frontend_install_read_env IMAGE_TAG "$env_file")"

  api_url="${api_url:-http://localhost/api/v1}"
  kc_realm="${kc_realm:-workspace-realm}"
  kc_client="${kc_client:-workspace-web}"
  build_id="${build_id:-install}"

  if ! frontend_dir="$(frontend_install_resolve_frontend_dir "$root_dir")"; then
    return 1
  fi

  if ! frontend_install_ensure_checkout "$frontend_dir"; then
    echo "ERROR: Could not prepare elt-frontend source at ${frontend_dir}" >&2
    return 1
  fi

  echo "Building install frontend as ${tag}"
  echo "  source=${frontend_dir}"
  echo "  NEXT_PUBLIC_KC_URL=${kc_url}"
  echo "  NEXT_PUBLIC_API_URL=${api_url}"

  if ! docker build -t "$tag" "$frontend_dir" \
    --build-arg "NEXT_PUBLIC_API_URL=${api_url}" \
    --build-arg "NEXT_PUBLIC_BUILD_ID=${build_id}" \
    --build-arg "NEXT_PUBLIC_KC_URL=${kc_url}" \
    --build-arg "NEXT_PUBLIC_KC_REALM=${kc_realm}" \
    --build-arg "NEXT_PUBLIC_KC_CLIENT_ID=${kc_client}"; then
    echo "ERROR: Frontend docker build failed." >&2
    return 1
  fi

  frontend_install_pin_frontend_image "$env_file" "$tag"
}
